# Generated by Django 4.1 on 2022-08-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
